# Generated by Django 5.2.3 on 2025-10-03 08:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECG_display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_duration_sec', models.PositiveIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ECG_display.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration_sec', models.PositiveIntegerField(default=60)),
                ('rhythm', models.CharField(default='sinus', max_length=40)),
                ('heart_rate', models.PositiveIntegerField(default=70)),
                ('spo2', models.PositiveIntegerField(default=98, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bis', models.PositiveIntegerField(default=45, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tof_count', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('tof_ratio', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('art_sys', models.PositiveIntegerField(default=120)),
                ('art_dia', models.PositiveIntegerField(default=70)),
                ('nibp_interval_sec', models.PositiveIntegerField(default=180)),
                ('nibp_sys', models.PositiveIntegerField(default=120)),
                ('nibp_dia', models.PositiveIntegerField(default=70)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='ECG_display.scenario')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
